<!--
    DATE:2022/2/1
    Author:旁观者
    FILE NAME:$NAME.ftlh
    By:IntelliJ IDEA
-->
<!DOCTYPE HTML>
<html>
<head>
    <#include "./common/meta.ftlh" />
    <title>首页</title>
    <#include "./common/style.ftlh" />
    <#include "./common/script.ftlh" />
</head>
<body>
    <div class="container-fluid">
        <#include "./common/header.ftlh" />
        <div class="row">
            <#include "common/leftNav.ftlh" />
        </div>
    </div>
</body>
</html>