-- auto Generated on 2022-02-13
-- DROP TABLE IF EXISTS archive;
CREATE TABLE archive(
	id VARCHAR (50) NOT NULL COMMENT '学/工号',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '姓名',
	age INT (11) NOT NULL DEFAULT -1 COMMENT '年龄',
	sex VARCHAR (50) NOT NULL DEFAULT '' COMMENT '性别',
	`type` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '账户类型',
	politic VARCHAR (50) NOT NULL DEFAULT '' COMMENT '政治面貌',
    nation VARCHAR (255) NOT NULL DEFAULT '汉族' COMMENT '民族',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'archive';
