use `school_system`;
-- auto Generated on 2021-11-08
-- DROP TABLE IF EXISTS dict;
CREATE TABLE dict(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`table_name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '表名',
	`column_name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '列名',
	type_code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '类型代码',
	type_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '类型名称',
	value_id INT (11) NOT NULL DEFAULT -1 COMMENT '数据数值',
	value_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '数据名称',
	`status` TINYINT (3) NOT NULL DEFAULT 0 COMMENT '类型状态',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'dict';
-- auto Generated on 2021-11-08
-- DROP TABLE IF EXISTS menu;
CREATE TABLE menu(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '菜单名称',
	parent_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT '父菜单Id',
	`level` INT (11) NOT NULL DEFAULT -1 COMMENT '菜单级别',
	url VARCHAR (50) NOT NULL DEFAULT '' COMMENT '菜单地址',
	menu_code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '菜单代码',
	icon_url VARCHAR (50) NOT NULL DEFAULT '' COMMENT '菜单图标地址',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'menu';
-- auto Generated on 2021-11-08
-- DROP TABLE IF EXISTS `role`;
CREATE TABLE `role`(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '角色名称',
	info VARCHAR (50) NOT NULL DEFAULT '' COMMENT '角色描述',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'role';
-- auto Generated on 2021-11-08
-- DROP TABLE IF EXISTS role_menu;
CREATE TABLE role_menu(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	role_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT '角色Id',
	menu_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT '菜单Id',
	info VARCHAR (50) NOT NULL DEFAULT '' COMMENT '角色权限分配描述',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'role_menu';
-- auto Generated on 2021-11-08
-- DROP TABLE IF EXISTS role_user;
CREATE TABLE role_user(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	role_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT '角色Id',
	user_id VARCHAR (50) NOT NULL DEFAULT '' COMMENT '用户Id',
	info VARCHAR (50) NOT NULL DEFAULT '' COMMENT '角色用户分配描述',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'role_user';
-- auto Generated on 2021-11-08
-- DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
	id VARCHAR (50) NOT NULL COMMENT '用户名',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '昵称',
	pass VARCHAR (50) NOT NULL DEFAULT '' COMMENT '密码',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	`status` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '用户状态',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user';
