use school_system;

-- auto Generated on 2022-04-08
-- DROP TABLE IF EXISTS sys_dict;
CREATE TABLE sys_dict(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '字典名称',
	`type` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '字典类型',
	code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '字典码',
	`value` INT (11) NOT NULL DEFAULT -1 COMMENT '字典值',
	`status` INT (11) NOT NULL DEFAULT -1 COMMENT '字典状态',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '数据字典';
